{
 "title": "Main",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor((node_time_seconds - node_boot_time_seconds)/3600/24)",
     "legendFormat": "days"
    },
    {
     "expr": "floor((node_time_seconds - node_boot_time_seconds)/3600)%24",
     "legendFormat": "hours"
    },
    {
     "expr": "floor((node_time_seconds - node_boot_time_seconds)/60)%60",
     "legendFormat": "minutes"
    }
   ]
  },
  {
   "title": "SSH",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"ssh.service\",state=\"active\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Redis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Docker",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"docker.service\",state=\"active\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pretix",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"pretix.service\",state=\"active\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 4 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load1" },
    { "expr": "node_load5", "legendFormat": "Load5" },
    { "expr": "node_load15", "legendFormat": "Load15" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "100*(1-rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "% Used RAM"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[30s]) / 1024^2",
     "legendFormat": "DOWN↓ {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[30s]) / 1024^2",
     "legendFormat": "UP↑ {{device}}"
    }
   ]
  },
  {
   "title": "Disk IO / min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{device=\"sda\"}[1m]) *60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes - node_filesystem_avail_bytes) / 1024^3",
     "legendFormat": "Disk used GB"
    },
    {
     "expr": "node_filesystem_size_bytes / 1024^3",
     "legendFormat": "Disk total GB"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Nginx active connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 23 },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "Active connections" }
   ]
  },
  {
   "title": "Nginx requests / min",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 23 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])*60",
     "legendFormat": "HTTP requests / min"
    }
   ]
  },
  {
   "title": "Pretix page views / min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(pretix_view_requests_total{status_code=\"200\"}[1m]) * 60)",
     "legendFormat": "Total HTTP 200"
    },
    {
     "expr": "sum(rate(pretix_view_requests_total{status_code=\"404\"}[1m]) * 60)",
     "legendFormat": "Total HTTP 404"
    },
    {
     "expr": "rate(pretix_view_requests_total{status_code=\"200\"}[1m]) * 60",
     "legendFormat": "{{url_name}}"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total[1m]) * 60",
     "legendFormat": "Processed commands / min"
    },
    {
     "expr": "rate(redis_total_reads_processed[1m]) * 60",
     "legendFormat": "Reads / min"
    },
    {
     "expr": "rate(redis_total_writes_processed[1m]) * 60",
     "legendFormat": "Writes / min"
    }
   ]
  },
  {
   "title": "Pretix DB size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"pretix\"} /1024^3",
     "legendFormat": "Pretix DB (MB)"
    }
   ]
  },
  {
   "title": "PostgreSQL queries",
   "type": "timeseries",
   "description": "Number of tuples",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_deleted{datname=\"pretix\"}[1m]) * 60",
     "legendFormat": "Deleted"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{datname=\"pretix\"}[1m]) * 60",
     "legendFormat": "Updated"
    },
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=\"pretix\"}[1m]) * 60",
     "legendFormat": "Inserted"
    },
    {
     "expr": "rate(pg_stat_database_tup_fetched{datname=\"pretix\"}[1m]) * 60",
     "legendFormat": "Fetched"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned{datname=\"pretix\"}[1m]) * 60",
     "legendFormat": "Returned"
    }
   ]
  }
 ]
}